name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v0.1.0)"
        required: true
        type: string

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-linux-amd64

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-linux-arm64

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-macos-amd64

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-macos-arm64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: litterbox-rust-upload.exe
            asset_name: litterbox-rust-upload-windows-amd64.exe

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: contains(matrix.target, 'aarch64-unknown-linux-gnu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare asset
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          cp ${{ matrix.artifact_name }} ../../../${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: ${{ matrix.asset_name }}
