name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v0.1.0)"
        required: true
        type: string

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # This is needed for creating releases
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-${{ github.event.inputs.version }}-linux-amd64

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-${{ github.event.inputs.version }}-macos-amd64

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: litterbox-rust-upload
            asset_name: litterbox-rust-upload-${{ github.event.inputs.version }}-macos-arm64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: litterbox-rust-upload.exe
            asset_name: litterbox-rust-upload-${{ github.event.inputs.version }}-windows-amd64.exe

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install OpenSSL (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare asset
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          cp ${{ matrix.artifact_name }} ../../../${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: ${{ matrix.asset_name }}
